import React from 'react';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { CTAOverlay } from './CTAOverlay';
import { CallToAction } from '../../types/annotation.types';

// Mock window.open
const mockWindowOpen = jest.fn();
Object.defineProperty(window, 'open', {
  writable: true,
  value: mockWindowOpen
});

const mockCTAs: CallToAction[] = [
  {
    id: 'cta-1',
    userId: 'user-1',
    documentId: 'doc-1',
    pageNumber: 1,
    url: 'https://example.com',
    label: 'Visit Example',
    coordinates: { x: 100, y: 200, width: 150, height: 50 },
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01')
  },
  {
    id: 'cta-2',
    userId: 'user-1',
    documentId: 'doc-1',
    pageNumber: 1,
    url: 'https://test.com/path?param=value',
    label: 'Test Link',
    coordinates: { x: 300, y: 400, width: 100, height: 30 },
    createdAt: new Date('2023-01-02'),
    updatedAt: new Date('2023-01-02')
  },
  {
    id: 'cta-3',
    userId: 'user-1',
    documentId: 'doc-1',
    pageNumber: 2,
    url: 'https://other.com',
    label: 'Other Page',
    coordinates: { x: 50, y: 100, width: 200, height: 40 },
    createdAt: new Date('2023-01-03'),
    updatedAt: new Date('2023-01-03')
  },
  {
    id: 'cta-4',
    userId: 'user-1',
    documentId: 'doc-1',
    pageNumber: 1,
    url: 'http://test.com/qr-link',
    label: 'QR Code Link',
    coordinates: { x: 200, y: 300, width: 120, height: 35 },
    createdAt: new Date('2023-01-04'),
    updatedAt: new Date('2023-01-04'),
    isAutoGenerated: true,
    qrCodeContent: 'qr-link',
    autoGeneratedAt: new Date('2023-01-04')
  }
];

const defaultProps = {
  callToActions: mockCTAs,
  pageNumber: 1,
  scale: 1,
  onCTAClick: jest.fn(),
  onCTAEdit: jest.fn(),
  onCTADelete: jest.fn()
};

describe('CTAOverlay', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  it('renders CTAs for the current page only', () => {
    render(<CTAOverlay {...defaultProps} />);
    
    // Should render 3 CTAs for page 1 (including auto-generated)
    const ctaElements = screen.getAllByRole('button');
    expect(ctaElements).toHaveLength(3);
    
    // Check that the CTAs have the correct labels
    expect(screen.getByLabelText('Call to action: Visit Example')).toBeInTheDocument();
    expect(screen.getByLabelText('Call to action: Test Link')).toBeInTheDocument();
    expect(screen.getByLabelText('Call to action: QR Code Link (Auto-generated from QR code)')).toBeInTheDocument();
    expect(screen.queryByLabelText('Call to action: Other Page')).not.toBeInTheDocument();
  });

  it('does not render anything when no CTAs exist for the page', () => {
    render(<CTAOverlay {...defaultProps} callToActions={[]} />);
    
    expect(screen.queryByRole('button')).not.toBeInTheDocument();
  });

  it('does not render CTAs for different pages', () => {
    render(<CTAOverlay {...defaultProps} pageNumber={3} />);
    
    expect(screen.queryByRole('button')).not.toBeInTheDocument();
  });

  it('opens URL in new tab when CTA is clicked', async () => {
    const user = userEvent.setup();
    render(<CTAOverlay {...defaultProps} />);
    
    const ctaElement = screen.getByLabelText('Call to action: Visit Example');
    await user.click(ctaElement);
    
    expect(mockWindowOpen).toHaveBeenCalledWith(
      'https://example.com',
      '_blank',
      'noopener,noreferrer'
    );
    expect(defaultProps.onCTAClick).toHaveBeenCalledWith(mockCTAs[0]);
  });

  it('opens URL with complex path and parameters', async () => {
    const user = userEvent.setup();
    render(<CTAOverlay {...defaultProps} />);
    
    const ctaElement = screen.getByLabelText('Call to action: Test Link');
    await user.click(ctaElement);
    
    expect(mockWindowOpen).toHaveBeenCalledWith(
      'https://test.com/path?param=value',
      '_blank',
      'noopener,noreferrer'
    );
    expect(defaultProps.onCTAClick).toHaveBeenCalledWith(mockCTAs[1]);
  });

  it('handles keyboard navigation with Enter key', async () => {
    const user = userEvent.setup();
    render(<CTAOverlay {...defaultProps} />);
    
    const ctaElement = screen.getByLabelText('Call to action: Visit Example');
    ctaElement.focus();
    await user.keyboard('{Enter}');
    
    expect(mockWindowOpen).toHaveBeenCalledWith(
      'https://example.com',
      '_blank',
      'noopener,noreferrer'
    );
    expect(defaultProps.onCTAClick).toHaveBeenCalledWith(mockCTAs[0]);
  });

  it('handles keyboard navigation with Space key', async () => {
    const user = userEvent.setup();
    render(<CTAOverlay {...defaultProps} />);
    
    const ctaElement = screen.getByLabelText('Call to action: Visit Example');
    ctaElement.focus();
    await user.keyboard(' ');
    
    expect(mockWindowOpen).toHaveBeenCalledWith(
      'https://example.com',
      '_blank',
      'noopener,noreferrer'
    );
    expect(defaultProps.onCTAClick).toHaveBeenCalledWith(mockCTAs[0]);
  });

  it('shows tooltip on hover', async () => {
    const user = userEvent.setup();
    render(<CTAOverlay {...defaultProps} />);
    
    const ctaElement = screen.getByLabelText('Call to action: Visit Example');
    await user.hover(ctaElement);
    
    await waitFor(() => {
      expect(screen.getByText('Visit Example')).toBeInTheDocument();
    });
  });

  it('hides tooltip on mouse leave', async () => {
    const user = userEvent.setup();
    render(<CTAOverlay {...defaultProps} />);
    
    const ctaElement = screen.getByLabelText('Call to action: Visit Example');
    await user.hover(ctaElement);
    
    await waitFor(() => {
      expect(screen.getByText('Visit Example')).toBeInTheDocument();
    });
    
    await user.unhover(ctaElement);
    
    await waitFor(() => {
      expect(screen.queryByText('Visit Example')).not.toBeInTheDocument();
    });
  });

  it('shows context menu on right click', async () => {
    const user = userEvent.setup();
    render(<CTAOverlay {...defaultProps} />);
    
    const ctaElement = screen.getByLabelText('Call to action: Visit Example');
    await user.pointer({ keys: '[MouseRight]', target: ctaElement });
    
    await waitFor(() => {
      expect(screen.getByText('Edit CTA')).toBeInTheDocument();
      expect(screen.getByText('Delete CTA')).toBeInTheDocument();
    });
  });

  it('calls onCTAEdit when edit is clicked in context menu', async () => {
    const user = userEvent.setup();
    render(<CTAOverlay {...defaultProps} />);
    
    const ctaElement = screen.getByLabelText('Call to action: Visit Example');
    await user.pointer({ keys: '[MouseRight]', target: ctaElement });
    
    await waitFor(() => {
      expect(screen.getByText('Edit CTA')).toBeInTheDocument();
    });
    
    await user.click(screen.getByText('Edit CTA'));
    
    expect(defaultProps.onCTAEdit).toHaveBeenCalledWith(mockCTAs[0]);
  });

  it('calls onCTADelete when delete is clicked in context menu', async () => {
    const user = userEvent.setup();
    render(<CTAOverlay {...defaultProps} />);
    
    const ctaElement = screen.getByLabelText('Call to action: Visit Example');
    await user.pointer({ keys: '[MouseRight]', target: ctaElement });
    
    await waitFor(() => {
      expect(screen.getByText('Delete CTA')).toBeInTheDocument();
    });
    
    await user.click(screen.getByText('Delete CTA'));
    
    expect(defaultProps.onCTADelete).toHaveBeenCalledWith('cta-1');
  });

  it('closes context menu when clicking outside', async () => {
    const user = userEvent.setup();
    const { container } = render(<CTAOverlay {...defaultProps} />);
    
    const ctaElement = screen.getByLabelText('Call to action: Visit Example');
    await user.pointer({ keys: '[MouseRight]', target: ctaElement });
    
    await waitFor(() => {
      expect(screen.getByText('Edit CTA')).toBeInTheDocument();
    });
    
    // Now the overlay container should have pointer-events: auto, so we can click it
    const overlayContainer = container.firstChild as Element;
    await user.click(overlayContainer);
    
    await waitFor(() => {
      expect(screen.queryByText('Edit CTA')).not.toBeInTheDocument();
    });
  });

  it('closes context menu when pressing Escape key', async () => {
    const user = userEvent.setup();
    render(<CTAOverlay {...defaultProps} />);
    
    const ctaElement = screen.getByLabelText('Call to action: Visit Example');
    await user.pointer({ keys: '[MouseRight]', target: ctaElement });
    
    await waitFor(() => {
      expect(screen.getByText('Edit CTA')).toBeInTheDocument();
    });
    
    fireEvent.keyDown(document, { key: 'Escape' });
    
    await waitFor(() => {
      expect(screen.queryByText('Edit CTA')).not.toBeInTheDocument();
    });
  });

  it('positions CTAs correctly based on coordinates', () => {
    render(<CTAOverlay {...defaultProps} />);
    
    const ctaElements = screen.getAllByRole('button');
    
    // Verify that CTAs are positioned (exact style testing is limited in jsdom)
    expect(ctaElements).toHaveLength(3); // 3 CTAs on page 1
    
    // Check that CTAs have the expected labels
    expect(screen.getByLabelText('Call to action: Visit Example')).toBeInTheDocument();
    expect(screen.getByLabelText('Call to action: Test Link')).toBeInTheDocument();
    expect(screen.getByLabelText('Call to action: QR Code Link (Auto-generated from QR code)')).toBeInTheDocument();
  });

  it('works without optional callback props', async () => {
    const user = userEvent.setup();
    render(
      <CTAOverlay 
        callToActions={mockCTAs} 
        pageNumber={1} 
        scale={1}
      />
    );
    
    const ctaElement = screen.getByLabelText('Call to action: Visit Example');
    await user.click(ctaElement);
    
    // Should still open the URL even without callbacks
    expect(mockWindowOpen).toHaveBeenCalledWith(
      'https://example.com',
      '_blank',
      'noopener,noreferrer'
    );
  });

  it('prevents event propagation when CTA is clicked', async () => {
    const user = userEvent.setup();
    const overlayClickHandler = jest.fn();
    
    render(
      <div onClick={overlayClickHandler}>
        <CTAOverlay {...defaultProps} />
      </div>
    );
    
    const ctaElement = screen.getByLabelText('Call to action: Visit Example');
    await user.click(ctaElement);
    
    // The overlay click handler should not be called
    expect(overlayClickHandler).not.toHaveBeenCalled();
    expect(mockWindowOpen).toHaveBeenCalled();
  });

  it('handles HTTP URLs correctly', async () => {
    const httpCTA: CallToAction = {
      ...mockCTAs[0],
      url: 'http://insecure-example.com',
      label: 'HTTP Link'
    };
    
    const user = userEvent.setup();
    render(
      <CTAOverlay 
        callToActions={[httpCTA]} 
        pageNumber={1} 
        scale={1}
        onCTAClick={defaultProps.onCTAClick}
      />
    );
    
    const ctaElement = screen.getByLabelText('Call to action: HTTP Link');
    await user.click(ctaElement);
    
    expect(mockWindowOpen).toHaveBeenCalledWith(
      'http://insecure-example.com',
      '_blank',
      'noopener,noreferrer'
    );
  });

  it('displays appropriate icons in CTA areas', () => {
    render(<CTAOverlay {...defaultProps} />);
    
    const ctaElements = screen.getAllByRole('button');
    
    // Check manual CTAs have link icon
    const manualCTAs = ctaElements.filter(cta => 
      cta.getAttribute('aria-label')?.includes('Visit Example') ||
      cta.getAttribute('aria-label')?.includes('Test Link')
    );
    manualCTAs.forEach(cta => {
      expect(cta).toHaveTextContent('🔗');
    });

    // Check auto-generated CTA has mobile icon
    const autoCTA = ctaElements.find(cta => 
      cta.getAttribute('aria-label')?.includes('QR Code Link')
    );
    expect(autoCTA).toHaveTextContent('📱');
  });

  it('has proper accessibility attributes', () => {
    render(<CTAOverlay {...defaultProps} />);
    
    const ctaElements = screen.getAllByRole('button');
    
    ctaElements.forEach((cta, index) => {
      expect(cta).toHaveAttribute('tabIndex', '0');
      expect(cta).toHaveAttribute('role', 'button');
      expect(cta).toHaveAttribute('aria-label');
      expect(cta).toHaveAttribute('title');
    });
  });

  describe('Auto-generated CTA visual distinction', () => {
    it('applies different styling to auto-generated CTAs', () => {
      render(<CTAOverlay {...defaultProps} />);
      
      const autoCTA = screen.getByLabelText('Call to action: QR Code Link (Auto-generated from QR code)');
      const manualCTA = screen.getByLabelText('Call to action: Visit Example');
      
      // Verify CTAs exist and have correct attributes
      expect(autoCTA).toBeInTheDocument();
      expect(manualCTA).toBeInTheDocument();
      
      // Check that different icons are used
      expect(autoCTA).toHaveTextContent('📱');
      expect(manualCTA).toHaveTextContent('🔗');
    });

    it('shows enhanced tooltip for auto-generated CTAs', async () => {
      const user = userEvent.setup();
      render(<CTAOverlay {...defaultProps} />);
      
      const autoCTA = screen.getByLabelText('Call to action: QR Code Link (Auto-generated from QR code)');
      await user.hover(autoCTA);
      
      await waitFor(() => {
        expect(screen.getByText('QR Code Link')).toBeInTheDocument();
        expect(screen.getByText('📱 Auto-generated from QR code')).toBeInTheDocument();
        expect(screen.getByText('QR Content: "qr-link"')).toBeInTheDocument();
      });
    });

    it('shows basic tooltip for manual CTAs', async () => {
      const user = userEvent.setup();
      render(<CTAOverlay {...defaultProps} />);
      
      const manualCTA = screen.getByLabelText('Call to action: Visit Example');
      await user.hover(manualCTA);
      
      await waitFor(() => {
        expect(screen.getByText('Visit Example')).toBeInTheDocument();
        expect(screen.queryByText('📱 Auto-generated from QR code')).not.toBeInTheDocument();
      });
    });

    it('includes auto-generation info in title attribute', () => {
      render(<CTAOverlay {...defaultProps} />);
      
      const autoCTA = screen.getByLabelText('Call to action: QR Code Link (Auto-generated from QR code)');
      const manualCTA = screen.getByLabelText('Call to action: Visit Example');
      
      expect(autoCTA).toHaveAttribute('title', 'QR Code Link - http://test.com/qr-link (Auto-generated from QR code)');
      expect(manualCTA).toHaveAttribute('title', 'Visit Example - https://example.com');
    });

    it('includes auto-generation info in aria-label', () => {
      render(<CTAOverlay {...defaultProps} />);
      
      const autoCTA = screen.getByLabelText('Call to action: QR Code Link (Auto-generated from QR code)');
      const manualCTA = screen.getByLabelText('Call to action: Visit Example');
      
      expect(autoCTA).toHaveAttribute('aria-label', 'Call to action: QR Code Link (Auto-generated from QR code)');
      expect(manualCTA).toHaveAttribute('aria-label', 'Call to action: Visit Example');
    });

    it('handles auto-generated CTAs without QR content in tooltip', async () => {
      const ctaWithoutQRContent: CallToAction = {
        id: 'cta-no-qr',
        userId: 'user-1',
        documentId: 'doc-1',
        pageNumber: 1,
        url: 'http://test.com/auto',
        label: 'Auto CTA No QR',
        coordinates: { x: 400, y: 500, width: 100, height: 30 },
        createdAt: new Date('2023-01-05'),
        updatedAt: new Date('2023-01-05'),
        isAutoGenerated: true,
        autoGeneratedAt: new Date('2023-01-05')
      };

      const user = userEvent.setup();
      render(
        <CTAOverlay 
          callToActions={[ctaWithoutQRContent]} 
          pageNumber={1} 
          scale={1}
          onCTAClick={defaultProps.onCTAClick}
        />
      );
      
      const autoCTA = screen.getByLabelText('Call to action: Auto CTA No QR (Auto-generated from QR code)');
      await user.hover(autoCTA);
      
      await waitFor(() => {
        expect(screen.getByText('Auto CTA No QR')).toBeInTheDocument();
        expect(screen.getByText('📱 Auto-generated from QR code')).toBeInTheDocument();
        expect(screen.queryByText(/QR Content:/)).not.toBeInTheDocument();
      });
    });

    it('positions auto-generated indicator correctly', () => {
      render(<CTAOverlay {...defaultProps} />);
      
      const autoCTA = screen.getByLabelText('Call to action: QR Code Link (Auto-generated from QR code)');
      
      // Note: Testing pseudo-elements is limited in jsdom, but we can verify the base element has the right styling
      // The dashed border and other styles are applied via CSS-in-JS
      expect(autoCTA).toBeInTheDocument();
      expect(autoCTA).toHaveAttribute('aria-label', 'Call to action: QR Code Link (Auto-generated from QR code)');
    });

    it('maintains consistent hover behavior for auto-generated CTAs', async () => {
      const user = userEvent.setup();
      render(<CTAOverlay {...defaultProps} />);
      
      const autoCTA = screen.getByLabelText('Call to action: QR Code Link (Auto-generated from QR code)');
      
      // Test hover interaction
      await user.hover(autoCTA);
      
      // Verify tooltip appears on hover
      await waitFor(() => {
        expect(screen.getByText('QR Code Link')).toBeInTheDocument();
      });
      
      await user.unhover(autoCTA);
      
      // Verify tooltip disappears
      await waitFor(() => {
        expect(screen.queryByText('QR Code Link')).not.toBeInTheDocument();
      });
    });
  });
});